# Generated by Django 3.2.9 on 2021-12-06 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('du', models.IntegerField()),
                ('Email personnel', models.EmailField(max_length=254, unique=True)),
                ('Email du travail', models.EmailField(max_length=254, unique=True)),
                ('photo enseignant', models.ImageField(upload_to='storage/images')),
            ],
        ),
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(upload_to='storage/images')),
                ('email', models.CharField(max_length=50)),
                ('etat_etudiant1', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('E', 'Exclu'), ('R', 'Retard')], default='P', max_length=50)),
                ('situatin', models.CharField(choices=[('R', 'Redoublant'), ('N', 'nouveau'), ('D', 'derogataire'), ('autre', 'autre')], default='N', max_length=50)),
                ('enseignant', models.ManyToManyField(to='UniversityApp.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500)),
                ('commentaire', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_groupe', models.CharField(max_length=25)),
                ('nbr_etudiants', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('NOM DU GROUPE', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('du', models.IntegerField()),
                ('Type du module', models.CharField(max_length=25)),
                ('niveau du module', models.CharField(max_length=25)),
                ('groupe', models.ManyToManyField(to='UniversityApp.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='outil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'materiel'), ('L', 'logiciel')], default='M', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='travail_a_rendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_lancement', models.DateField(default=datetime.datetime(2021, 12, 6, 22, 6, 43, 857011, tzinfo=utc))),
                ('date_limite_retour', models.DateField()),
                ('nature', models.CharField(max_length=100)),
                ('descriptif', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('EN_COURS', 'en cours'), ('TERMINEE', 'terminée'), ('ANNULEE', 'annulée'), ('DIFFEREE', 'differée')], default='EN_COURS', max_length=10)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.etudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.evaluation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.module')),
            ],
        ),
        migrations.CreateModel(
            name='seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_de_debut', models.DateTimeField(default=datetime.datetime(2021, 12, 6, 22, 6, 43, 857820))),
                ('heure_de_fin', models.DateTimeField(default=datetime.datetime(2021, 12, 6, 22, 6, 43, 857839))),
                ('num_salle', models.IntegerField(blank=True)),
                ('Objectif', models.CharField(max_length=1000)),
                ('Resume', models.CharField(max_length=1000)),
                ('etat', models.CharField(blank=True, choices=[('C', 'En_cours'), ('T', 'Terminee'), ('A', 'Anulee'), ('D', 'Differee')], max_length=8)),
                ('type', models.CharField(choices=[('N', 'Normale'), ('R', 'Rattrapage'), ('S', 'Soutien'), ('F', 'Formation')], max_length=10)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.module')),
                ('outils', models.ManyToManyField(to='UniversityApp.outil')),
            ],
        ),
        migrations.CreateModel(
            name='piece_attache_rendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('titre', models.CharField(max_length=100)),
                ('travail_a_rendre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.travail_a_rendre')),
            ],
        ),
        migrations.CreateModel(
            name='piece_attache_enonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000, unique=True)),
                ('titre', models.CharField(max_length=100)),
                ('travail_a_rendre', models.ManyToManyField(to='UniversityApp.travail_a_rendre')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='idgroupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.groupe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='module',
            field=models.ManyToManyField(to='UniversityApp.module'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.enseignant'),
        ),
        migrations.CreateModel(
            name='enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('idseance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.seance')),
            ],
        ),
        migrations.CreateModel(
            name='absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('motif', models.CharField(max_length=100)),
                ('justification', models.CharField(max_length=100)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniversityApp.seance')),
            ],
        ),
    ]
