# Generated by Django 3.2.9 on 2021-12-14 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travail_a_rendre',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='travail_a_rendre',
            name='etudiants',
            field=models.ManyToManyField(to='UniversityApp.etudiant'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='photo enseignant',
            field=models.ImageField(upload_to='photos/enseignants'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(upload_to='photos/etudiants'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='email',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_de_debut',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 22, 10, 20, 86890)),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_de_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 22, 10, 20, 86909)),
        ),
        migrations.AlterField(
            model_name='travail_a_rendre',
            name='date_lancement',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 22, 10, 20, 85643, tzinfo=utc)),
        ),
    ]
