# Generated by Django 4.0 on 2021-12-15 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityApp', '0002_auto_20211214_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='NOM DU GROUPE',
        ),
        migrations.AddField(
            model_name='groupe',
            name='niveau',
            field=models.CharField(default='1ere', max_length=25),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_de_debut',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 21, 27, 9, 446150)),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_de_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 21, 27, 9, 446170)),
        ),
        migrations.AlterField(
            model_name='travail_a_rendre',
            name='date_lancement',
            field=models.DateField(default=datetime.datetime(2021, 12, 15, 21, 27, 9, 444804, tzinfo=utc)),
        ),
    ]
